---
- hosts: Local
  tasks:

  - name: Snap Packages
    ansible.builtin.shell: snap install "{{ item }}" --classic
    become: true
    loop:
      - code
      - bitwarden
      - discord

  - name: Add Support for 32 bit
    ansible.builtin.shell: dpkg --add-architecture i386
    become: true

  - name: Import Steam GPG keybindings
    ansible.builtin.apt_key:
      url: http://repo.steampowered.com/steam/archive/stable/steam.gpg
      state: present
    become: true

  - name: Clean up old Steam sources
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    become: true
    loop:
      - /etc/apt/sources.list.d/steam.list 
      - /etc/apt/sources.list.d/steam-beta.list

  - name: Add Steam repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64,i386] http://repo.steampowered.com/steam/ stable steam"
      state: present
      filename: "steam"
    become: true

  - name: Add Docker GPG keybindings
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: Add Docker repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable"
      state: present
      filename: "docker"
    become: true

  - name: Download Docker Desktop
    get_url:
      url: https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb
      dest: /tmp/docker-desktop.deb
    become: true

  - name: Install Docker Desktop
    apt:
      deb: /tmp/docker-desktop.deb
    become: true

  - name: Update apt cache
    apt:
      update_cache: yes
    become: true

  - name: install  packages
    apt:
      name: "{{ item }}"
      state: present
    loop: 
      - autoconf
      - automake
      - bash
      - clang-format
      - cmake
      - coreutils
      - dos2unix
      - fping
      - gnupg
      - htop
      - p7zip
      - pbzip2
      - pigz
      - tmux
      - vim
      - w3m
      - wget
      - zsh
      - zsh-syntax-highlighting
      - npm
      - redis
      - tree
      - jq
      - yarn
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - software-properties-common
      - apt-transport-https
      - curl
      - libgl1-mesa-dri:amd64
      - libgl1-mesa-dri:i386
      - wireshark
      - redshift-gtk
      - onedrive
    become: true

  - name: Deploy Updated Profiles
    template:
      backup: true
      dest: "~/.{{ item }}rc"
      src: "templates/{{ item }}_profile"
    loop:
      - "zsh"
      - "bash"

  - name: Setup Oh My Zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      creates: "~/.oh-my-zsh/oh-my-zsh.sh"

  - name: Download Zsh Theme
    get_url:
      url: https://raw.githubusercontent.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme
      dest: "~/.oh-my-zsh/custom/themes/bullet-train.zsh-theme"

  - name: Create Fonts Directory
    file:
      path: "~/.fonts/"
      state: directory
      owner: pclemens
      group: pclemens
      mode: '0755'

  - name: Setup Fonts
    connection: local
    copy:
      src: "{{ item }}"
      dest: "/home/pclemens/.fonts/"
      owner: pclemens
      group: pclemens
      mode: '0755'
    with_fileglob:
      - fonts/*.ttf

  - name: Install VS Code Extentions
    shell: code --install-extension {{ item }}
    loop:
     - "eamodio.gitlens"
     - "coenraads.bracket-pair-colorizer-2"
     - "docsmsft.docs-markdown"
     - "oderwat.indent-rainbow"
     - "yzhang.markdown-all-in-one"
     - "redhat.vscode-yaml"
     - dracula-theme.theme-dracula
